%handels changes in concentrations due to chemical reactions
J = photolysis(Jphoto,sun.zenith); %calculates photolysis rates


eBVOC(z,t) = emit_BVOC(z,LAI(z), LAIcum(z), Eb, T, PAR, Er,nus,absncanopy)/H(z,r);
[DepNO2,DepH2O2,DepO3,DepHCHO,DepHNO3,DepNO,gst(t)] = deposition(gst,t,timehr( start_t, t, dt),T, lw(z),z,RH,PAR,f_light,LAIcum(z),Rsoil,Vcut, Vst, H(z,r),u_os,g_min,VPD_min, VPD_max,SWP_min, SWP_max,SWP,SGS ,EGS, gpot_a , gpot_b, gpot_c,hhti,hlti,vegtype,depscheme, Ptorr);
DepPAN = 0;DepNO2;
if z == 1
    eNO = soil_NO(timehr( start_t, t, dt),EbNO_max,EbNO_min,tshift_no,days, T,H(z,r));
    FluxNOx(1,t) = eNO*H(z,r);
    Fluxtracer(1,t) = FluxNOx(1,t);
else 
    eNO = 0;
end 


dtracer_C = eNO*dt;

dO3_C = (J.NO2*Er*NO2(z,t)...
      + J.NO3b*Er*NO3(z,t)...
      + kOHselfa(T,M)*OH(z,t)*OH(z,t)...
      + kHO2CH3COO2(T,M)*CH3COO2(z,t)*HO2(z,t)...
      - kNOO3(T,M)*NO(z,t)*O3(z,t)...
      - kOHO3(T,M)*OH(z,t)*O3(z,t)...
      - (J.O3*Er*kO1DH2O(T,M)/(kO1DN2(T,M)*M))*O3(z,t)*H2O ...
      - kHO2O3(T,M)*HO2(z,t)*O3(z,t)...
      - kNO2O3(T,M)*NO2(z,t)*O3(z,t)...
      - DepO3*O3(z,t)*LAI(z)...
      )*dt;
        
dNO_C = (eNO...
      + J.NO2*Er*NO2(z,t)...
      + J.NO3a*Er*NO3(z,t)...
      - kNOO3(T,M)*NO(z,t)*O3(z,t)...
      - kNOHO2(T,M)*HO2(z,t)*NO(z,t) ...
      - kNONO3(T,M)*NO(z,t)*NO3(z,t)...
      - kNOCH3O2(T,M)*CH3O2(z,t)*NO(z,t)...
      - kNOCH3COO2(T,M)*CH3COO2(z,t)*NO(z,t)...
      - kNORO2(T,M)*RO2(z,t)*NO(z,t)...
      -DepNO*(NO(z,t))*LAI(z)...
      )*dt;
    
  
dNO2_C = (kNOO3(T,M)*NO(z,t)*O3(z,t)...
       + J.HNO3*Er*HNO3(z,t)...
       + kNOHO2(T,M)*HO2(z,t)*NO(z,t)...
       + 2*kNO3self(T,M)*NO3(z,t)...
       + 2*kNONO3(T,M)*NO(z,t)*NO3(z,t)...
       + kNOCH3O2(T,M)*CH3O2(z,t)*NO(z,t)...
       + kN2O5_decomp(T,M)*N2O5(z,t)...
       + J.NO3b*Er*NO3(z,t)...
       + kNOCH3COO2(T,M)*CH3COO2(z,t)*NO(z,t)...
       + kpan_decomp(T,M)*PAN(z,t)...
       + (1-a)*kNORO2(T,M)*RO2(z,t)*NO(z,t)...
       + (1-Ba)*kNO3*VOC(z,t)*NO3(z,t)...
       - J.NO2*Er*NO2(z,t)...
       - kOHNO2a(T,M)*NO2(z,t)*OH(z,t)...
       - DepNO2*NO2(z,t)*LAI(z) ...
       - kNO2O3(T,M)*NO2(z,t)*O3(z,t)...
       - kNO2NO3(T,M)*NO3(z,t)*NO2(z,t)...
       - kNO2CH3COO2(T,M)*CH3COO2(z,t)*NO2(z,t)...
       )*dt;
         %+ (1-Bi)*kNO3isoprene(T,M)*isoprene(z,t)*NO3(z,t)...
 dHO2_C = (kOHO3(T,M)*O3(z,t)*OH(z,t)...
        + kOHH2O2(T,M)*H2O2(z,t)*OH(z,t)...
        + kCOOHa(T,M)*CO*OH(z,t)...
        + kOHH2CO(T,M)*CH2O(z,t)*OH(z,t)...
        + 2*J.CH2O*Er*CH2O(z,t)...
        + kNOCH3O2(T,M)*CH3O2(z,t)*NO(z,t)...
        + (1-a)*kNORO2(T,M)*RO2(z,t)*NO(z,t)...
        - kHO2O3(T,M)*O3(z,t)*HO2(z,t)...
        - kOHHO2(T,M)*OH(z,t)*HO2(z,t)...
        - 2*kHO2self(T,M,H2O)*HO2(z,t)*HO2(z,t)...
        - kHO2CH3O2(T,M)*CH3O2(z,t)*HO2(z,t)...
        - kHO2CH3COO2(T,M)*CH3COO2(z,t)*HO2(z,t) ...
        - 0.5*kHO2RO2(T,M)*RO2(z,t)*HO2(z,t)...
        )*dt;
    
dHNO3_C = (kOHNO2a(T,M)*NO2(z,t)*OH(z,t)...
        + kH2ON2O5(T,M)*N2O5(z,t)*H2O...
        + kNO3CH3CHO(T,M)*CH3CHO(z,t)*NO3(z,t)...
        - 0*J.HNO3*Er*HNO3(z,t)...
        - DepHNO3*HNO3(z,t)*LAI(z)...
        )*dt;
        
dH2O2_C = (kHO2self(T,M,H2O)*HO2(z,t)*HO2(z,t)...
        + kOHselfb(T,M)*OH(z,t)*OH(z,t)...
        - J.H2O2*Er*H2O2(z,t)...
        - kOHH2O2(T,M)*H2O2(z,t)*OH(z,t)...
        - DepH2O2*H2O2(z,t)*LAI(z)...
        )*dt;
    
dN2O5_C = (kNO2NO3(T,M)*NO3(z,t)*NO2(z,t)...
        - kH2ON2O5(T,M)*N2O5(z,t)*H2O...
        - kN2O5_decomp(T,M)*N2O5(z,t)...
        )*dt;

dNO3_C = (kNO2O3(T,M)*NO2(z,t)*O3(z,t)...
       + kN2O5_decomp(T,M)*N2O5(z,t)...
       - kNO2NO3(T,M)*NO3(z,t)*NO2(z,t)...
       - kNONO3(T,M)*NO(z,t)*NO3(z,t)...
       - 2*kNO3self(T,M)*NO3(z,t)...
       - J.NO3a*Er*NO3(z,t)-J.NO3b*Er*NO3(z,t)...
       - kNO3CH3CHO(T,M)*CH3CHO(z,t)*NO3(z,t)...
       - kNO3*NO3(z,t)*VOC(z,t)...
       )*dt;   
        
dCH3O2_C = (kOHCH4(T,M)*CH4*OH(z,t)...
         + 0.7*kOHCH3OOH(T,M)*CH3OOH(z,t)*OH(z,t)...
         + kNOCH3COO2(T,M)*CH3COO2(z,t)*NO(z,t)...
         + kCH3COO2self(T,M)*CH3COO2(z,t) *CH3COO2(z,t)...
         + 1.2*kRO2self(T,M)*RO2(z,t)*RO2(z,t) ...
         + 0.6*kRO2self(T,M)*RO2(z,t)*CH3O2(z,t)...
         - kHO2CH3O2(T,M)*CH3O2(z,t)*HO2(z,t)...
         - kNOCH3O2(T,M)*CH3O2(z,t)*NO(z,t)...
         - kCH3O2CH3COO2(T,M)*CH3COO2(z,t)*CH3O2(z,t)...
         )*dt;
     
dCH3OOH_C = (kHO2CH3O2(T,M)*CH3O2(z,t)*HO2(z,t)...
          + kCH3O2CH3COO2(T,M)*CH3COO2(z,t)*CH3O2(z,t)...
          + kHO2CH3COO2(T,M)*CH3COO2(z,t)*HO2(z,t)...
          - kOHCH3OOH(T,M)*CH3OOH(z,t)*OH(z,t)...
          )*dt;
 
dCH2O_C = (0.3*kOHCH3OOH(T,M)*CH3OOH(z,t)*OH(z,t)...
        + kCH3O2CH3COO2(T,M)*CH3COO2(z,t)*CH3O2(z,t)...
        - kOHH2CO(T,M)*CH2O(z,t)*OH(z,t)...
        - J.CH2O*Er*CH2O(z,t)+kNOCH3O2(T,M)*CH3O2(z,t)*NO(z,t)...
        - DepHCHO*CH2O(z,t)*LAI(z)...
        )*dt;

dCH3CHO_C = (acet_f*eBVOC(z,t)...
          - kOHCH3CHO(T,M)*CH3CHO(z,t)*OH(z,t)...
          - kNO3CH3CHO(T,M)*CH3CHO(z,t)*NO3(z,t)...
          )*dt;

      
dPAN_C = (kNO2CH3COO2(T,M)*CH3COO2(z,t)*NO2(z,t)...
          - kpan_decomp(T,M)*PAN(z,t)...
      -DepPAN*PAN(z,t)*LAI(z))*dt;
        
dCH3COO2_C = (kOHC2H5CHO(T,M)*CH3CHO(z,t)*OH(z,t)...
           + kNO3CH3CHO(T,M)*CH3CHO(z,t)*NO3(z,t)...
           + kpan_decomp(T,M)*PAN(z,t)...
           - kNO2CH3COO2(T,M)*CH3COO2(z,t)*NO2(z,t) ...
           - kNOCH3COO2(T,M)*CH3COO2(z,t)*NO(z,t)...
           - kCH3O2CH3COO2(T,M)*CH3COO2(z,t)*CH3O2(z,t)...
           - kHO2CH3COO2(T,M)*CH3COO2(z,t)*HO2(z,t)...
           - 2*kCH3COO2self(T,M)*CH3COO2(z,t)*CH3COO2(z,t)...
           )*dt;

dVOC_C = (eBVOC(z,t)...
    -kOH*VOC(z,t)*OH(z,t)...
    -kNO3*NO3(z,t)*VOC(z,t)...
    )*dt;

        
 dRO2_C = (kOH*VOC(z,t)*OH(z,t)...
        - kNORO2(T,M)*NO(z,t)*RO2(z,t)...
        - kHO2RO2(T,M)*RO2(z,t)*HO2(z,t)...
        - 2*kRO2self(T,M)*RO2(z,t)*RO2(z,t)...
        - kRO2self(T,M)*RO2(z,t)*CH3O2(z,t)...        
        )*dt;   

dRONO2_C = (a*kNORO2(T,M)*RO2(z,t)*NO(z,t)...
    + Ba*kNO3*VOC(z,t)*NO3(z,t)...
    )*dt;
        
  
 %***update species concentrations
        O3(z,t) = O3(z,t) + dO3_C;
        NO(z,t) = NO(z,t) + dNO_C;
        NO2(z,t) = NO2(z,t) + dNO2_C;
        HO2(z,t) = HO2(z,t) + dHO2_C;
        HNO3(z,t) = HNO3(z,t) + dHNO3_C;
        H2O2(z,t) = H2O2(z,t) + dH2O2_C;
        N2O5(z,t) = N2O5(z,t) + dN2O5_C;
        NO3(z,t) = NO3(z,t) +dNO3_C;   
        CH3O2(z,t) = CH3O2(z,t) + dCH3O2_C;
        CH3OOH(z,t) = CH3OOH(z,t) + dCH3OOH_C;
        CH2O(z,t) = CH2O(z,t) + dCH2O_C;
        CH3CHO(z,t) = CH3CHO(z,t) + dCH3CHO_C;
        PAN(z,t) = PAN(z,t) + dPAN_C;
        CH3COO2(z,t) = CH3COO2(z,t) + dCH3COO2_C;
        VOC(z,t) = VOC(z,t) + dVOC_C;
        RO2(z,t) = RO2(z,t) + dRO2_C; 
        RONO2(z,t) = RONO2(z,t) + dRONO2_C;
        tracer(z,t) = tracer(z,t) + dtracer_C;

%% ***sets OH to steady state
POH = 2*(J.O3*Er*kO1DH2O(T,M)/(kO1DN2(T,M)*M))*O3(z,t)*H2O...
    + kHO2O3(T,M)*O3(z,t)*HO2(z,t)...
    + 2*J.H2O2*Er*H2O2(z,t)...
    + kNOHO2(T,M)*HO2(z,t)*NO(z,t)...
    + 0.5*kHO2RO2(T,M)*RO2(z,t)*HO2(z,t)...
    + kRO2(T,M)*RO2(z,t);
        %+ J.HNO3*Er*HNO3(z,t)...
LOH = kOHO3(T,M)*O3(z,t)...
    + kOHHO2(T,M)*HO2(z,t)...
    + kOHH2O2(T,M)*H2O2(z,t)...
    + kOHNO2a(T,M)*NO2(z,t)...
    + kCOOHa(T,M)*CO...
    + kOHCH4(T,M)*CH4...
    + kOHCH3OOH(T,M)*CH3OOH(z,t)...
    + kOHH2CO(T,M)*CH2O(z,t)...
    + kOHCH3CHO(T,M)*CH3CHO(z,t)...
    + kOH*VOC(z,t)...
    + kOHselfa(T,M)*OH(z,t)...
    + kOHselfb(T,M)*OH(z,t);
          
 
  VOCR = kOHCO(T,M)*CO + kOHCH4(T,M)*CH4 + kOHC2H5CHO(T,M)*CH3CHO(z,t) + kOH*VOC(z,t);%
  
  aa = 2*(kHO2self(T,M,H2O)+kRO2self(T,M)+kHO2RO2(T,M))*(VOCR/(kNORO2(T,M)*NO(z,t)*(1-a)))^2;
  b = kOHNO2a(T,M)*NO2(z,t) + kNORO2(T,M)*a*VOCR/(kNORO2(T,M)*(1-a));
  c = -(2*(J.O3*Er*kO1DH2O(T,M)/(kO1DN2(T,M)*M))*O3(z,t)*H2O + 2*J.CH2O*Er*CH2O(z,t));
  
   if NO2(z,t)==0
       OH(z,t) = 0;
   else
       OH_calc = roots([aa b c]);
       OH_calc= OH_calc(imag(OH_calc)==0);
       if length(OH_calc(OH_calc<=0))==2 || isempty(OH_calc)
           OH(z,t) = 0;
       else 
           OH(z,t) = OH_calc(OH_calc > 0);
       end
   end
 
 if OH(z,t)==0
     RO2(z,t)=0;
     HO2(z,t)=0;
 else
     RO2(z,t) = VOCR*OH(z,t)/(kNORO2(T,M)*NO(z,t)*(1-a));
     HO2(z,t) = RO2(z,t);
 end

%% calculates NOx lifetimes in model domain
LHNO3(z,t) = kOHNO2a(T,M).*OH(z,t).*NO2(z,t) + 2.*kH2ON2O5(T,M).*H2O.*N2O5(z,t)...
          + kNO3CH3CHO(T,M).*CH3CHO(z,t).*NO3(z,t);
LDepNOx(z,t) = (DepNO2.*NO2(z,t)+ DepNO.*NO(z,t)).*LAI(z) ;
LRONO2(z,t) = a.*kNORO2(T,M).*RO2(z,t).*NO(z,t)...
    + Ba*kNO3*VOC(z,t)*NO3(z,t);

LPAN(z,t) = kNO2CH3COO2(T,M).*CH3COO2(z,t).*NO2(z,t);



p_o3 = kNOHO2(T,M).*HO2(:,t).*NO(:,t) + kNOCH3O2(T,M).*CH3O2(:,t).*NO(:,t)+(1-a).*kNORO2(T,M).*RO2(:,t).*NO(:,t);
P_O3(t)= sum(H(:,t).*p_o3)./(box(7,t));

L_NOx(t)=(sum(H(:,t).*LDepNOx(:,t),1)+sum(H(:,t).*LHNO3(:,t),1)+sum(H(:,t).*LRONO2(:,t),1))./box(7,t);

OPE(t)= P_O3(t)./L_NOx(t);

p_o3 = kNOHO2(T,M).*HO2(1:absncanopy,t).*NO(1:absncanopy,t) + kNOCH3O2(T,M).*CH3O2(1:absncanopy,t).*NO(1:absncanopy,t)+(1-a).*kNORO2(T,M).*RO2(1:absncanopy,t).*NO(1:absncanopy,t);
P_O3(t)= sum(H(1:absncanopy,t).*p_o3)./(box(absncanopy,t));

L_NOx(t)=(sum(H(1:absncanopy,t).*LDepNOx(1:absncanopy,t),1)+sum(H(1:absncanopy,t).*LHNO3(1:absncanopy,t),1)+sum(H(1:absncanopy,t).*LRONO2(1:absncanopy,t),1))./box(absncanopy,t);

OPE_can(t) = P_O3(t)./L_NOx(t);

if z ==7
    height= H(:,r);
    heightcanopy = H(1:absncanopy,r);
    

end    


    
%% *******Reactions used********;
 
% ***** NOx + Ox chemistry ********:
% NO + O3 -> NO2 + O2    ;
% NO2 + hv + O2 -> NO + O3   ;
 
% ***** HOx  chemistry ********:
% O3 + hv + H2O -> O2 + OH +OH ;
% OH + O3 -> HO2 + O2;
% HO2 + O3 -> OH + O2 + O2 ;
% OH + OH -> H2O2 ;
% OH + HO2 -> H2O + O2;
% HO2 + HO2 -> H2O2 + O2;
% H2O2 + OH -> HO2 + H2O;
% H2O2 + hv -> OH + OH;
% NO2 + OH + M -> HNO3 + M;
% HNO3 + hv -> NO2 + OH;
% HO2 + NO -> OH + NO2;
 
%********nighttime chemistry*******
% NO2 + O3 -> NO3 + O2;
% NO3 + NO2 + M -> N2O5 + M;
% N2O5 + H2O -> 2HNO3 ;
% NO + NO3 -> 2 NO2;
% N2O5 -> NO2 + NO3 ;
% NO3 + hv -> NO + O2               
% NO3 + hv+ O2 -> NO2 + O3    
 
%*******CH4**************;
% CO + OH -> CO2 + HO2    
% CH4 + OH -> CH3O2 + H2O    
% CH3O2 + HO2 -> CH3OOH + O2   
% CH3O2 + NO +O2-> CH2O + HO2 + NO2      
% CH3OOH + OH -> CH2O + OH + H2O   
% CH3OOH + OH -> CH3O2 + H2O   
% CH3OOH + hv+O2 -> CH2O + HO2 + OH     
% CH2O + OH -> CO + HO2 + H2O   
% CH2O + hv + 2O2 -> CO + 2HO2  

%********Acetaldehyde chemistry************;
% CH3CHO + OH + O2 -> CH3COO2 + H2O     
% CH3COO2 + NO2 -> PAN                
% CH3COO2 + NO +O2-> NO2 + CO2 + CH3O2     
% CH3COO2 + CH3O2 -> CH2O + O2 + CH3COOH   
% CH3COO2 + HO2 -> O3 + CH3COOH        
% CH3COO2 + CH3COO2 -> O2 + 2CO2 + 2CH3   
% CH3CHO + NO3 -> HNO3 + CH3COO2  
% PAN -> CH3COO2 + NO2  k41*PAN;

%***********alkyl nitrate production ******
% apinene + OH -> RO2
% isoprene + OH ->RO2
% RO2 + NO -> (1-a)HO2 + (1-a)NO2 + aRONO2
% RO2 + HO2 -> 0.5ROOH + 0.5O2 + 0.5HO2 + 0.5OH
% RO2 + RO2 -> 1.2CH3O2 + products;
% RO2 + CH3O2 -> 0.6CH3O2 + 0.6HO2 + products;
% apinene  + NO3 -> BaRONO2 + (1-Ba)NO2 + products;
% isoprene  + NO3 -> BiRONO2 + (1-Bi)NO2 + products;

%*****ozone + BVOC criegee chemistry****
% isoprene  + O3 -> 0.5HO2+0.5CO+0.5OH+0.5CH2O + products;
% apinene  + O3 -> OH + products;

        